/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PIO0_0 (number 36), LuxServo
  @{ */
#define BOARD_INITPINS_LuxServo_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LuxServo_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LuxServo_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_26 (number 18), LS_Zigi
  @{ */
#define BOARD_INITPINS_LS_Zigi_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LS_Zigi_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_Zigi_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_27 (number 17), LS_PET
  @{ */
#define BOARD_INITPINS_LS_PET_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LS_PET_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_PET_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_28 (number 7), LS_Bier
  @{ */
#define BOARD_INITPINS_LS_Bier_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LS_Bier_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_Bier_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_1 (number 24), Fan
  @{ */
#define BOARD_INITPINS_Fan_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_Fan_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Fan_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
