/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PIO0_0 (number 36), LuxServo
  @{ */
#define BOARD_INITPINS_LuxServo_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LuxServo_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LuxServo_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_24 (number 20), TXD
  @{ */
#define BOARD_INITPINS_TXD_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_TXD_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TXD_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_25 (number 19), RXD
  @{ */
#define BOARD_INITPINS_RXD_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_RXD_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RXD_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
