/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.0
processor: LPC845
package_id: LPC845M301JBD48
mcu_data: ksdk2_0
processor_version: 13.0.1
pin_labels:
- {pin_num: '11', pin_signal: PIO1_0/CAPT_X1, label: LEDG, identifier: LEDG}
- {pin_num: '14', pin_signal: PIO1_1/CAPT_X2, label: LEDB, identifier: LEDB}
- {pin_num: '16', pin_signal: PIO1_2/CAPT_X3, label: LEDR, identifier: LEDR}
- {pin_num: '26', pin_signal: PIO0_8/XTALIN, label: STEP_EN, identifier: STEP_EN}
- {pin_num: '25', pin_signal: PIO0_9/XTALOUT, label: STEP_MS1, identifier: STEP_MS1}
- {pin_num: '13', pin_signal: PIO0_10/I2C0_SCL, label: STEP_MS2, identifier: STEP_MS2}
- {pin_num: '12', pin_signal: PIO0_11/I2C0_SDA, label: STEP_STEP, identifier: STEP_STEP}
- {pin_num: '2', pin_signal: PIO0_13/ADC_10, label: STEP_DIR, identifier: STEP_DIR}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
